### ISSUE TITLE
Best way to make it responsive?

### ISSUE THREAD

**Issue by juanjoabarca** [alnitak/atoms#1]
Thanks for sharing this work, it's hard to find good animations for flutter projects, it's not my specialty.

What is the best way to make it adapt to screen changes?
for example a website.
Thank you!

**Comment by alnitak** [comment]
Hi @juanjoabarca,

thanks for reporting this. I have updated with a fix for this problem. Now when the widget resizes, all the parameters are updated for example in a desktop app or a browser. 
Please try it!

**Comment by juanjoabarca** [comment]
works fine, thanks for the good job!
